### ISSUE TITLE
Reason to upgrade to v3 of API?

### ISSUE THREAD

**Issue by barelyknown** [emq/workable#6]
Thanks for releasing this!

I noticed that workable's API is on v3 now. Have you thought about upgrading this gem to use it?

[Here's what they said the new version on their site](https://workable.readme.io/docs/whats-new-in-v3#breaking-changes). They say that v2 will continue to work but is deprecated.

**Comment by emq** [comment]
Hello Sean!

I wasn't aware that workable already released v3 API, thanks for the heads up :). I will try prepare PR this month to keep the gem up to date (but no promises when it comes to exact release date, I’m swamped atm).

 /cc @mpapis

**Comment by barelyknown** [comment]
Sounds good! I'm using the `workable` gem as is and it's working just fine for now. :+1:

**Comment by emq** [comment]
Ok, definitely not going to happen this month, it was a crazy week, but it's on my list! :)
