### ISSUE TITLE
Example of workable collection usage

### ISSUE THREAD

**Issue by j-dexx** [emq/workable#8]
Hi, I thought it might be useful to add an example of how to use workable collections.

Basically just:
```
client = Workable::Client.new(api_key: 'api_key', subdomain: 'your_subdomain')
jobs = client.jobs
loop do
  jobs.each do |job|
    # Do something with the job
  end
  break unless jobs.next_page?
  jobs = jobs.fetch_next_page
end
```

Using loop because it's matz's [preference](http://rosettacode.org/wiki/Loops/Do-while#Ruby)

Would you like me to add it?  If so where would you like it?  Using yard in the workable collection class?  Or in the readme?

**Comment by emq** [comment]
Hi, sorry for slight delay, was pretty occupied lately; and sure - feel free to add this info, I think readme should be just fine (somewhere under _usage_) - as it's loaded by yard anyway. Thanks!

**Comment by j-dexx** [comment]
Sorry for the double commit - hadn't realised I changed the gitignore on the first one to ignore rubymine files.
